language: android
dist: trusty
android:
  components:
    - build-tools-29.0.2
    - android-29
    - extra
  licenses:
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
script:
  - "./gradlew clean build assemble -PdisablePreDex --stacktrace"